// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Lancefy_Display

#include "../ui.h"

void ui_dataDisplay_screen_init(void)
{
    ui_dataDisplay = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_dataDisplay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_dataDisplay);
    lv_img_set_src(ui_Image5, &ui_img_banner_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 180
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 400);

}
