// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Lancefy_Display

#ifndef _LANCEFY_DISPLAY_UI_H
#define _LANCEFY_DISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
extern lv_obj_t * ui_mainScreen;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image13;
void ui_event_startButton(lv_event_t * e);
extern lv_obj_t * ui_startButton;
extern lv_obj_t * ui_butonStatus;
extern lv_obj_t * ui_Image1;
// SCREEN: ui_dataDisplay
void ui_dataDisplay_screen_init(void);
extern lv_obj_t * ui_dataDisplay;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_banner_png);    // assets/Banner.png
LV_IMG_DECLARE(ui_img_1184185672);    // assets/lancefy-text-logo-shadow.png
LV_IMG_DECLARE(ui_img_1962740327);    // assets/lancefy-text-logo.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
